Repository ipno-llead/processing, pull requests merged in 2021-08, with the labels that each got.

#69 Miscellaneous bug fixes #1
  clean/grand_isle_pd.py
  clean/ipm_new_orleans_pd_cprr_allegations.py
  clean/tangipahoa_so_cprr.py
  data/datavalid.yml
  lib/clean.py
  lib/clean_test.py
  notebooks/combined.ipynb
  notebooks/grand_isle_pd.ipynb
  notebooks/ipm_new_orleans_pd_cprr_allegations.ipynb
  raw_datasets.json
  requirements.txt
  scripts/rawfiles.sh
Labels: bug

#64 Enhancement/baton rouge pd
  clean/baton_rouge_pd_cprr.py
  clean/baton_rouge_so_cprr.py
  clean/lafayette_so.py
  clean/post_pprr.py
  data/.wrglsync.yaml
  fuse/baton_rouge_pd.py
  fuse/baton_rouge_so.py
  fuse/greenwood_pd.py
  fuse/plaquemines_so.py
  fuse/ponchatoula_pd.py
  fuse/tangipahoa_so.py
  lib/clean_test.py
  lib/events_test.py
  match/baton_rouge_pd.py
  match/baton_rouge_so.py
  match/ponchatoula_pd.py
  notebooks/combined.ipynb
  notebooks/ipm_new_orleans_iapro_pprr.ipynb
  notebooks/lafayette_pd.ipynb
  notebooks/ponchatoula_pd.ipynb
  raw_datasets.json
Labels: bug, enhancement

#70 Process Ponchatoula PD CPRR
  clean/ponchatoula_pd.py
  data/.wrglsync.yaml
  fuse/all.py
  fuse/ponchatoula_pd.py
  match/ponchatoula_pd.py
  notebooks/ponchatoula_pd.ipynb
  raw_datasets.json
Labels: enhancement

#72 Enhancement/new orleans so
  clean/new_orleans_so_cprr.py
  fuse/lafayette_so.py
  fuse/new_orleans_so.py
  lib/events.py
  match/new_orleans_so.py
  raw_datasets.json
Labels: enhancement
