Repository ipno-llead/processing, pull requests merged in 2021-07, with the labels that each got.

#29 Enhancement/tangipahoa so
  .flake8
  .idea/.name
  .vscode/launch.json
  .vscode/settings.json
  Makefile
  clean/brusly_pd.py
  clean/ipm_new_orleans_iapro_pprr.py
  clean/madisonville_csd_pprr.py
  clean/madisonville_pd_cprr.py
  clean/tangipahoa_so_cprr.py
  data/.wrglsync.yaml
  fuse/all.py
  fuse/brusly_pd.py
  fuse/madisonville_pd.py
  fuse/scott_pd.py
  fuse/tangipahoa_so.py
  match/tangipahoa_so.py
  notebooks/tangipahoa_so_cprr_2015_2021.ipynb
  scripts/download_input.py
Labels: enhancement

#30 Clean data for Shreveport PD
  .github/workflows/pr_flake8.yml
  Makefile
  clean/shreveport_pd_cprr.py
  data/.wrglsync.yaml
  fuse/all.py
  fuse/shreveport_pd.py
  match/shreveport_pd.py
  notebooks/shreveport_pd.ipynb
  scripts/download_input.py
Labels: enhancement

#32 Bug/louisiana state csc
  clean/st_tammany_so_pprr.py
  scripts/download_input.py
Labels: bug

#33 Bug/mandeville pd
  clean/grand_isle_pd.py
  clean/mandeville_pd.py
  match/grand_isle_pd.py
  scripts/download_input.py
Labels: bug

#35 Bug/grand isle pd
  clean/grand_isle_pd.py
  match/grand_isle_pd.py
  scripts/download_input.py
Labels: bug

#42 Bug/ipm new orleans iapro pprr
  clean/baton_rouge_csd_pprr.py
  clean/grand_isle_pd.py
  clean/ipm_new_orleans_iapro_pprr.py
  match/grand_isle_pd.py
  scripts/download_input.py
Labels: bug

#38 Enhancement/lafayette so
  Makefile
  clean/grand_isle_pd.py
  clean/lafayette_so.py
  clean/post_pprr.py
  data/.wrglsync.yaml
  fuse/lafayette_so.py
  match/grand_isle_pd.py
  match/lafayette_so.py
  notebooks/lafayette_so.ipynb
Labels: enhancement

#43 Bug/events
  Makefile
  clean/baton_rouge_csd_pprr.py
  clean/caddo_parish_so_pprr.py
  clean/covington_pd.py
  clean/gretna_pd.py
  clean/ipm_new_orleans_iapro_pprr.py
  clean/kenner_pd.py
  clean/mandeville_pd.py
  clean/new_orleans_harbor_pd_pprr.py
Labels: bug

#44 Enhancement/lafayette so
  clean/grand_isle_pd.py
  match/grand_isle_pd.py
Labels: bug

#45 Bug/events
  Makefile
  clean/baton_rouge_csd_pprr.py
  clean/caddo_parish_so_pprr.py
  clean/covington_pd.py
  clean/grand_isle_pd.py
  clean/gretna_pd.py
  clean/ipm_new_orleans_iapro_pprr.py
  clean/kenner_pd.py
  clean/new_orleans_harbor_pd_pprr.py
  match/grand_isle_pd.py
Labels: bug

#47 Add EditorConfig file
  .editorconfig
  .vscode/extensions.json
Labels: enhancement

#46 Enhancement/louisiana csd pprr 2021
  Makefile
  clean/louisiana_csd_pprr_2021.py
  fuse/louisiana_state_csc.py
  lib/personnel.py
  notebooks/louisiana_csd_pprr.ipynb
Labels: enhancement

#48 Updating Shreveport PD allegation with codebook
  .vscode/settings.json
  Makefile
  clean/shreveport_pd_cprr.py
  fuse/shreveport_pd.py
  match/shreveport_pd.py
  notebooks/shreveport_pd.ipynb
  scripts/download_input.py
Labels: enhancement

#50 Bug/end of line
  .flake8
  Makefile
  clean/baton_rouge_csd_pprr.py
  clean/caddo_parish_so_pprr.py
  clean/covington_pd.py
  clean/grand_isle_pd.py
  clean/gretna_pd.py
  clean/ipm_new_orleans_iapro_pprr.py
  clean/kenner_pd.py
  clean/lafayette_so.py
  clean/mandeville_pd.py
  clean/new_orleans_harbor_pd_pprr.py
  clean/post_pprr.py
  data/.wrglsync.yaml
  fuse/lafayette_so.py
  fuse/tangipahoa_so.py
  match/grand_isle_pd.py
  match/lafayette_so.py
  match/tangipahoa_so.py
  notebooks/lafayette_so.ipynb
  scripts/download_input.py
Labels: bug

#49 Bug/events
  .vscode/extensions.json
  .vscode/settings.json
  clean/louisiana_csd_pprr_2021.py
  clean/port_allen_csd_pprr.py
  clean/shreveport_pd_cprr.py
  clean/slidell_pd.py
  clean/st_tammany_so_cprr.py
  clean/st_tammany_so_pprr.py
  clean/vivian_csd.py
  fuse/louisiana_state_csc.py
  fuse/shreveport_pd.py
  lib/personnel.py
  match/shreveport_pd.py
  notebooks/louisiana_csd_pprr.ipynb
  notebooks/shreveport_pd.ipynb
Labels: bug

#58 Process Lafayette PD PPRR (2010-2021) and CPRR (2015-2020)
  Makefile
  clean/lafayette_pd.py
  data/.wrglsync.yaml
  fuse/all.py
  fuse/lafayette_pd.py
  lib/columns.py
  lib/events.py
  lib/standardize.py
  match/lafayette_pd.py
  match/new_orleans_so.py
  match/tangipahoa_so.py
  notebooks/lafayette_pd.ipynb
  requirements.txt
  scripts/download_input.py
Labels: enhancement

#53 Process Baton Rouge PD PPRR 2021
  Makefile
  clean/baton_rouge_csd_pprr.py
  clean/baton_rouge_pd_cprr.py
  clean/baton_rouge_pd_pprr.py
  fuse/baton_rouge_pd.py
  match/baton_rouge_pd.py
  notebooks/baton_rouge_pd.ipynb
  scripts/download_input.py
Labels: enhancement

#60 Enhancement/lafayette pd split action
  clean/lafayette_pd.py
  lib/events_test.py
  lib/standardize.py
  lib/standardize_test.py
  notebooks/lafayette_pd.ipynb
Labels: enhancement

#54 Process Ponchatoula PD
  Makefile
  clean/ponchatoula_pd.py
  data/.wrglsync.yaml
  fuse/all.py
  fuse/ponchatoula_pd.py
  match/ponchatoula_pd.py
  notebooks/ponchatoula_pd.ipynb
  scripts/download_input.py
Labels: enhancement

#59 Enhancement/hammond pd
  clean/hammond_pd_cprr.py
  data/.wrglsync.yaml
  fuse/all.py
  fuse/hammond_pd.py
  match/hammond_pd.py
  notebooks/baton_rouge_pd.ipynb
  notebooks/hammond_pd_cprr.ipynb
Labels: enhancement

#61 Cleanup July 27
  Makefile
  clean/baton_rouge_so_cprr.py
  clean/brusly_pd.py
  clean/hammond_pd_cprr.py
  clean/ipm_new_orleans_iapro_pprr.py
  clean/new_orleans_harbor_pd_cprr.py
  clean/scott_pd_pprr.py
  clean/tangipahoa_so_cprr.py
  data/.wrglsync.yaml
  data/datavalid.yml
  fuse/baton_rouge_pd.py
  fuse/hammond_pd.py
  lib/clean.py
  lib/standardize.py
  match/hammond_pd.py
  notebooks/combined.ipynb
  notebooks/ipm_new_orleans_iapro_pprr.ipynb
  notebooks/lafayette_pd.ipynb
  scripts/download_input.py
Labels: bug, enhancement

#62 Update cross agency match script
  match/cross_agency.py
Labels: enhancement
