Repository ipno-llead/processing, pull requests merged in 2021-05, with the labels that each got.

#6 Replace lib/match with datamatch v0.1.0
  clean/port_allen_pd_cprr.py
  lib/match/__init__.py
  lib/match/indices.py
  lib/match/indices_test.py
  lib/match/matchers.py
  lib/match/matchers_test.py
  lib/match/similarities.py
  lib/match/similarities_test.py
  match/baton_rouge_da.py
  match/baton_rouge_pd.py
  match/baton_rouge_so.py
  match/brusly_pd.py
  match/caddo_parish_so.py
  match/covington_pd.py
  match/grand_isle_pd.py
  match/greenwood_pd.py
  match/gretna_pd.py
  match/harahan_pd.py
  match/kenner_pd.py
  match/levee_pd.py
  match/louisiana_state_csc.py
  match/madisonville_pd.py
  match/mandeville_pd.py
  match/new_orleans_harbor_pd.py
  match/new_orleans_pd.py
  match/plaquemines_so.py
  match/port_allen_pd.py
  match/slidell_pd.py
  match/st_tammany_so.py
  match/vivian_pd.py
  notebooks/baton_rouge_fpcsb.ipynb
  notebooks/baton_rouge_pd.ipynb
  notebooks/baton_rouge_so.ipynb
  notebooks/brusly_pd.ipynb
  notebooks/madisonville_csd_pprr.ipynb
  notebooks/new_orleans_harbor_pd_pprr_2010-2020.ipynb
  notebooks/new_orleans_pd_pprr.ipynb
  notebooks/post_pprr.ipynb
  notebooks/st_tammany_so.ipynb
  requirements.txt
Labels: enhancement

#9 Add label check for pull request
  .github/workflows/pullrequest.yml
Labels: enhancement

#12 Process/scott pd
  Makefile
  clean/baton_rouge_so_cprr.py
  clean/scott_pd_cprr.py
  data/.wrglsync.yaml
  fuse/all.py
  fuse/scott_pd.py
  match/scott_pd.py
  scripts/download_input.py
Labels: enhancement

#14 Fix some errors for Baton Rouge SO and Scott PD
  Makefile
  clean/baton_rouge_so_cprr.py
  clean/scott_pd_cprr.py
  match/scott_pd.py
  scripts/download_input.py
Labels: bug

#15 Remove bi-weekly salary for Slidell PD
  clean/slidell_pd.py
  notebooks/slidell_pd.ipynb
Labels: bug

#16 Add docstring to everything under lib
  clean/ipm_new_orleans_iapro_pprr.py
  lib/clean.py
  lib/columns.py
  lib/date.py
  lib/events.py
  lib/exceptions.py
  lib/explore.py
  lib/path.py
  lib/personnel.py
  lib/post.py
  lib/ref.py
  lib/rows.py
  lib/split_schema.py
  lib/standardize.py
  lib/textract.py
  lib/translate.py
  lib/uid.py
  notebooks/baton_rouge_pd.ipynb
  notebooks/gretna_pd_pprr_2018.ipynb
  notebooks/ipm_new_orleans_pd_cprr_allegations.ipynb
  notebooks/new_orleans_csd_pprr_09-15-2020.ipynb
Labels: documentation

#8 Process New Orleans SO CPRR 2019
  Makefile
  clean/new_orleans_so_cprr.py
  data/.wrglsync.yaml
  data/datavalid.yml
  fuse/all.py
  fuse/covington_pd.py
  fuse/new_orleans_so.py
  lib/clean.py
  lib/columns.py
  lib/events.py
  match/new_orleans_so.py
  notebooks/new_orleans_so_cprr.ipynb
  requirements.txt
Labels: enhancement
