Repository ipno-llead/processing, pull requests merged in 2022-03, with the labels that each got.

#259 Add TimedAccessor
  lib/pandas_extensions.py
  requirements.txt
Labels: enhancement

#260 bugs/misc
  clean/st_tammany_so_cprr.py
Labels: bug

#258 Enhancement/nopd
  .wrgl/config.yaml
  clean/new_orleans_pd_uof.py
  data/datavalid.yml
  data/raw.dvc
  fuse/all.py
  fuse/new_orleans_pd.py
  lib/clean.py
  lib/columns.py
  match/new_orleans_pd.py
Labels: documentation, enhancement

#263 Enhancement/lafourche_so_allegations
  .wrgl/config.yaml
  clean/lafourche_so_cprr.py
  data/raw.dvc
  fuse/all.py
  fuse/lafourche_so.py
  match/lafourche_so.py
Labels: enhancement

#262 enhancement/st_john_so_allegations
  .wrgl/config.yaml
  clean/st_john_cprr.py
  data/raw.dvc
  fuse/all.py
  fuse/st_john_so.py
  match/st_john_so.py
Labels: enhancement

#264 Enhancement/lafayette_so_awards
  .wrgl/config.yaml
  clean/lafayette_so_awards.py
  data/datavalid.yml
  fuse/all.py
  fuse/lafayette_so.py
  lib/clean.py
  lib/columns.py
  match/lafayette_so.py
Labels: enhancement

#225 enhancement/canonicalize_names function
  clean/new_orleans_pd_uof.py
  data/datavalid.yml
  lib/clean.py
  lib/clean_test.py
  lib/events_test.py
  match/hammond_pd.py
  match/new_orleans_so.py
  match/tangipahoa_so.py
Labels: enhancement

#270 bug/test_clean_sexes
  lib/clean_test.py
Labels: bug

#271 enhancement/cprr_ascension_so_2019_2021
  .wrgl/config.yaml
  clean/ascension_so_cprr.py
  data/datavalid.yml
  data/raw.dvc
  fuse/all.py
  fuse/ascension_so.py
  match/ascension_so.py
Labels: enhancement

#272 bug/deduplicate
  clean/ipm_new_orleans_iapro_pprr.py
  clean/madisonville_pd_cprr.py
  clean/new_orleans_harbor_pd_cprr.py
  clean/new_orleans_pd_award.py
  clean/new_orleans_so_cprr.py
  clean/west_monroe_pd_cprr.py
  fuse/baton_rouge_pd.py
  fuse/bossier_city_pd.py
  fuse/caddo_parish_so.py
  fuse/jefferson_so.py
  fuse/lafayette_so.py
  fuse/new_orleans_pd.py
  fuse/plaquemines_so.py
  fuse/rayne_pd.py
  fuse/st_tammany_so.py
  match/baton_rouge_pd.py
  match/bossier_city_pd.py
  match/caddo_parish_so.py
  match/hammond_pd.py
  match/houma_pd.py
  match/jefferson_so.py
  match/lafayette_pd.py
  match/lafayette_so.py
  match/lake_charles_pd.py
  match/new_orleans_da.py
  match/new_orleans_pd.py
  match/new_orleans_so.py
  match/plaquemines_so.py
  match/rayne_pd.py
  match/st_tammany_so.py
  match/tangipahoa_so.py
Labels: bug
