Repository ipno-llead/processing, pull requests merged in 2022-01, with the labels that each got.

#224 bug/wrgl-config.yaml
  .wrgl/config.yaml
Labels: bug

#223 enhancement/appeals
  .wrgl/config.yaml
  clean/baton_rouge_fpcsb_lprr.py
  clean/new_orleans_csc_lprr.py
  data/datavalid.yml
  fuse/all.py
Labels: enhancement

#213 enhancement/allegations_acadia_so
  .wrgl/config.yaml
  clean/acadia_so_cprr.py
  fuse/acadia_so.py
  fuse/all.py
  match/acadia_so.py
  raw_datasets.json
Labels: enhancement

#227 Enhancement/allegations_west_monroe_pd_2020
  .wrgl/config.yaml
  clean/west_monroe_pd_cprr.py
  fuse/all.py
  fuse/west_monroe_pd.py
  match/west_monroe_pd.py
  raw_datasets.json
Labels: enhancement

#228 enhancement/cprr_abbeville_pd_2015_2018
  clean/abbeville_pd_cprr.py
  fuse/abbeville_pd.py
  match/abbeville_pd.py
  raw_datasets.json
Labels: enhancement

#232 Fix broken wrgl link
  README.md
Labels: documentation

#230 enhancement/personnel_and_events
  fuse/all.py
Labels: enhancement

#233 enhancement/pprr_baker_pd
  clean/baker_pd_pprr.py
  fuse/baker_pd.py
  match/baker_pd.py
  raw_datasets.json
Labels: enhancement

#234 Enhancement/pprr lake charles pd
  clean/lake_charles_pd_pprr.py
  fuse/lake_charles_pd.py
  match/lake_charles_pd.py
  raw_datasets.json
Labels: enhancement

#237 enhancement/allegations_st_landry_so_2020
  .wrgl/config.yaml
  clean/st_landry_so_cprr.py
  fuse/all.py
  fuse/st_landry_so.py
  match/st_landry_so.py
  raw_datasets.json
Labels: enhancement

#238 Enhancement/allegations_erath_pd
  .wrgl/config.yaml
  clean/erath_pd_cprr.py
  data/datavalid.yml
  fuse/all.py
  fuse/erath_pd.py
  match/erath_pd.py
  raw_datasets.json
Labels: enhancement

#240 enhancement/allegations_benton_pd_2015_2021
  .wrgl/config.yaml
  clean/benton_pd_cprr.py
  fuse/all.py
  fuse/benton_pd.py
  match/benton_pd.py
  raw_datasets.json
Labels: enhancement

#242 enhancement/cameron_so_2015_2019
  clean/cameron_so_cprr.py
  fuse/cameron_so.py
  match/cameron_so.py
  raw_datasets.json
Labels: enhancement

#248 enhancement/personnel_rayne_pd
  .wrgl/config.yaml
  clean/rayne_pd_pprr.py
  fuse/all.py
  fuse/rayne_pd.py
  match/rayne_pd.py
Labels: enhancement

#247 enhancement/allegations_eunice_pd_2019_2021
  .wrgl/config.yaml
  clean/eunice_pd_cprr.py
  fuse/all.py
  fuse/eunice_pd.py
  match/eunice_pd.py
  raw_datasets.json
Labels: enhancement
